name: nip49
description: NIP-49 Private Key Encryption for Nostr protocol - encrypt/decrypt private keys with passwords.
version: 1.1.1
repository: https://github.com/nogringo/nip49
topics:
  - nostr
  - nip49

environment:
  sdk: ^3.8.1

dependencies:
  cryptography: ^2.7.0
  bech32: ^0.2.2
  convert: ^3.1.2
  pointycastle: ^3.9.1
  unorm_dart: ^0.3.1+1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
