name: nip49
description: NIP-49 Private Key Encryption for Nostr protocol - encrypt/decrypt private keys with passwords.
version: 1.0.0
repository: https://github.com/nogringo/nip49
topics:
  - nostr
  - nip49

environment:
  sdk: ^3.8.1

dependencies:
  cryptography: ^2.7.0
  bech32: ^0.2.2
  convert: ^3.1.2
  typed_data: ^1.4.0
  pointycastle: ^4.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
